# PyFlex Configuration File
#
# Author: Matt Oswalt (http://keepingitclassless.net)
#
# This configuration file houses all of the dymanically populated information
# that makes it's way into an NXOS configuration script through Jinja2
# templates.
#
# Refer to the README for more details on how to use this tool.

# Sections
#
# Use this section to determine which portions of the infrastructure are built
sections:
    - ucs
#    - netapp
#    - nexus
#    - vsphere



# Authentication
#
# Enter authentication information here
auth:
    ucs:
        host: 10.12.0.74
        user: admin
        pass: cisco
    netapp:
        host: 10.12.0.70
        user: admin
        pass: netapp
    nexusa:
        host: 10.12.0.100
        user: admin
        pass: cisco
    nexusb:
        host: 10.12.0.101
        user: admin
        pass: cisco
    vcenter:
        host: 10.12.0.15
        user: DOMAIN\admin
        pass: vmware

# General
#
# Define general configuration options hee
general:
    org: ORG_TEST #Define org name here, or if no suborg, write "root"
    mgmtgw: 10.1.1.1
    ntp: 
        - 192.168.11.10
        - 192.168.11.11
    snmp:
        traphost: 10.102.2.100

# UCS Configuration
#
# Configuration items specific to UCS
ucs:
    pools: #Only creating a single block for everything, just to get stuff working. May consider coming back to allow for multiple pools/purposes, but not sure if anyone really uses that idea.
        mac:
            A:
                blockbegin: 00:25:B5:00:A0:00
                blockend: 00:25:B5:00:A0:FF
            B:
                blockbegin: 00:25:B5:00:B0:00
                blockend: 00:25:B5:00:B0:FF
        wwpn:
            A:
                blockbegin: 20:00:00:25:B5:00:A0:00
                blockend: 20:00:00:25:B5:00:A0:FF
            B:
                blockbegin: 20:00:00:25:B5:00:B0:00
                blockend: 20:00:00:25:B5:00:B0:FF
# VLANS
#
# Defines the VLANs and their corresponding names/descriptions that should be
# placed on the switch.
#
# Format is a key/value pair, where VLAN ID is the key, and name/description is
# the corresponding value.
vlans:
    mgmt:
        240: ESX_MGMT_10.1.40.0
    prod:
        109: Core_Services_10.1.9.0
        232: 1000v-Control_10.1.32.0
        234: CIFS_10.1.34.0
        241: vMotion_10.1.41.0
        249: Corporate-VMs_10.1.49.0
        260: NFS_10.1.160.0

#TODO: Can't have forward slashes here, or actually in most places, as it screws up MO paths.

# VSANS
#
# Defines the VSANs and their corresponding names/descriptions that should be
# placed on the switch.
#
# Format is a key/value pair, where VSAN ID is the key, and name/description is
# the corresponding value.
vsans:
    a:
        235: FCoE_Fabric_A
    b:
        236: FCoE_Fabric_B

# QOS
#
# Specifies some parameters to be used in a standard MQC-style configuration
qos:
    defaultmtu: 1500 # The MTU to be used on class-default 
                     # (unclassified) traffic

# PORTS
#
# Specifies general configuration settings for individual ports. Many ports 
# receive more specific configuration as part of the "feature installation"
# option in future versions, but this is a handy way to make en masse changes
# first.
ports:
    trunks:
        "e1/1-48"
        #TODO: need to make this not a simple string - probably a list

# STORAGE
#
# Storage configuration
storage: #revisit this - might not need to expose all of these
    var_na_portset: fcoe_pset_1
    var_na_vserver: FC_VS1
    var_na_vserverRootVol: = FC_VS1_root
    var_na_bootVol: /vol/FC_BootVol1/ #Needs to be of this format, including the forward slashes. LUN will be appended without any slashes