# PyFlex Configuration File
#
# Author: Matt Oswalt (http://keepingitclassless.net)
#
# This configuration file houses all of the dymanically populated information
# for a Flexpod. 
#
# Refer to the README for more details on how to use this tool.

# Workers
#
# Use this section to determine which portions of the infrastructure are built
workers:
    - ucs
#    - netapp
#    - nexus
#    - vsphere



# Authentication
#
# Enter authentication information here
auth:
    ucs:
        host: 10.12.0.97
        user: "config"
        pass: "config"
    netapp:
        host: 10.12.0.70
        user: admin
        pass: netapp
    nexusa:
        host: 10.12.0.100
        user: admin
        pass: cisco
    nexusb:
        host: 10.12.0.101
        user: admin
        pass: cisco
    vcenter:
        host: 10.12.0.15
        user: DOMAIN\admin
        pass: vmware

# General
#
# Define general configuration options hee
general:
    mgmtgw: 10.1.1.1
    ntp: 
        - 192.168.11.10
        - 192.168.11.11
    snmp:
        traphost: 10.102.2.100

# UCS Configuration
#
# Configuration items specific to UCS
ucs:
    org: TEST_ORG #Define org name here, or if no suborg, write "root"
    pools:
        ip:
            start: 10.15.0.50
            end: 10.15.0.100
            mask: 255.255.255.0
            gw: 10.15.0.1
        mac:
            A:
                blockbegin: 00:25:B5:00:A0:00
                blockend: 00:25:B5:00:A1:FF
            B:
                blockbegin: 00:25:B5:00:B0:00
                blockend: 00:25:B5:00:B1:FF
        wwpn:
            A:
                blockbegin: 20:00:00:25:B5:00:A0:00
                blockend: 20:00:00:25:B5:00:A1:FF
            B:
                blockbegin: 20:00:00:25:B5:00:B0:00
                blockend: 20:00:00:25:B5:00:B1:FF
        wwnn:
                blockbegin: 20:00:00:25:B5:00:F0:00
                blockend: 20:00:00:25:B5:00:F1:FF
        uuid:
                blockbegin: 0000-000000000001
                blockend: 0000-000000000100
    links: 4-link #Links per chassis; options are 1-link, 2-link, 4-link, 8-link, or platform-max
    sptname: ESXi_SPT
    spprefix: ESXi-
    vnicprefix: ESXi-
    numbertospawn: 4
    vlangroups: #A temporary measure to map the groups of VLANs to the vNICs they belong to.
        ESX-MGMT: mgmt
        ESX-NFS: nfs
        ESX-PROD: prod

# VLANS
#
# Defines the VLANs and their corresponding names/descriptions that should be
# placed on the switch.
#
# Format is a key/value pair, where VLAN ID is the key, and name/description is
# the corresponding value.
#
# As of now, the use of forward slashes is not allowed, as it currently messes with MO paths 
#
# Also it is very important to provide a Unique name/description for each VLAN ID provided. 
# UCS currently uses this value to determine VLAN membership. It's also just good sense.
vlans:
    mgmt:
        10: ESX_MGMT_172.16.10.0
        20: ESX_VMOT_172.16.20.0
    nfs:
        99: NFS_172.16.99.0
    prod:
        60: Server1_172.16.60.0
        70: Server2_172.16.70.0


# VSANS
#
# Defines the VSANs and their corresponding names/descriptions that should be
# placed on the switch.
#
# Format is a key/value pair, where VSAN ID is the key, and name/description is
# the corresponding value.
vsans:
    a:
        235: FCoE_Fabric_A
    b:
        236: FCoE_Fabric_B

# QOS
#
# Specifies some parameters to be used in a standard MQC-style configuration
qos:
    defaultmtu: 1500 # The MTU to be used on class-default  (unclassified) traffic
    classes:
        Gold: none
        Silver: none
        Bronze: none
        Best-Effort: full


### BELOW IS UNIMPLEMENTED ###

# # PORTS
# #
# # Specifies general configuration settings for individual ports. Many ports 
# # receive more specific configuration as part of the "feature installation"
# # option in future versions, but this is a handy way to make en masse changes
# # first.
# ports:
#     trunks:
#         "e1/1-48"
#         #TODO: need to make this not a simple string - probably a list

# # STORAGE
# #
# # Storage configuration
# storage: #revisit this - might not need to expose all of these
#     var_na_portset: fcoe_pset_1
#     var_na_vserver: FC_VS1
#     var_na_vserverRootVol: = FC_VS1_root
#     var_na_bootVol: /vol/FC_BootVol1/ #Needs to be of this format, including the forward slashes. LUN will be appended without any slashes
#     targets:
#         A:
#             - "50:00:00:00:00:00:00:00"
#             - "50:00:00:00:00:00:00:01"
#         B:
#             - "50:00:00:00:00:00:00:02"
#             - "50:00:00:00:00:00:00:03"